Repository vaadin/react-components, pull requests merged in 2023-06, with the labels that each got.

#121 refactor: use better building approach
  .github/workflows/validation.yml
  karma.config.cjs
  package-lock.json
  package.json
  scripts/build.ts
  scripts/generator.ts
  scripts/utils/misc.ts
  src/GridFilterColumn.tsx
  src/Select.tsx
  src/renderers/useRenderer.ts
  src/utils/createComponent.ts
  test/kitchen-sink/DialogComponent.tsx
  test/kitchen-sink/Row5.tsx
  test/kitchen-sink/Row9.tsx
  test/utils/createOverlayCloseCatcher.ts
  tsconfig.build.json
  tsconfig.json
  vite.config.ts
Labels: hilla

#117 chore: enable build for the 2.1 branch
  .github/workflows/validation.yml
Labels: target/1.3, target/2.0, target/2.1

#103 Revert "fix: workaround empty web-types.json in @vaadin/confirm-dialog@24.1.0-alpha9"
  scripts/descriptions.ts
  scripts/utils/settings.ts
Labels: hilla, target/2.1

#128 fix: copy d.ts files to the build
  package.json
  scripts/copy-dts.ts
Labels: hilla, target/1.3, target/2.0, target/2.1
